version: "3.3"

networks:
  spice:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_BASE:-172.20.1}.0/24
          gateway: ${NETWORK_BASE:-172.20.1}.1


services:
  mongodb:
    build: ../db
    #name: spice/communitymodel/db
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-spiceComMod}
      - MONGODB_USER=${MONGODB_USER:-spice}
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - TYPE=$TYPE
    networks:
      spice:
        ipv4_address: ${NETWORK_BASE:-172.20.1}.3
#    user: ${UID:-1000}:${GUID:-1000}
  app:
    depends_on:
      - mongodb
      - cm
    build: ../apiServer
    #name: spice/communitymodel/app
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_LOG_COLLECTION=log_api
      - DB_USER=${MONGODB_USER:-spice}
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=${MONGODB_DATABASE:-spiceComMod}
      - DB_PORT=27017
      - NODE_DOCKER_PORT=${APP_CONTAINER_PORT:-8080}
      - CM_DOCKER_PORT=${CM_CONTAINER_PORT:-8090}
      - API_USER=${API_USER:-user}
      - API_PASS=${API_PASS:-pass}
      - TYPE=$TYPE
    networks:
      spice:
        ipv4_address: ${NETWORK_BASE:-172.20.1}.2
  cm:
    depends_on:
      - mongodb
    image: cm
    build: ../cmServer
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_LOG_COLLECTION=log_cm
      - DB_USER=${MONGODB_USER:-spice}
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=${MONGODB_DATABASE:-spiceComMod}
      - DB_PORT=27017
      - CM_DOCKER_PORT=${CM_CONTAINER_PORT:-8090}
      - TYPE=$TYPE
    networks:
      spice:
        ipv4_address: ${NETWORK_BASE:-172.20.1}.4
